### ISSUE TITLE
Checkboxes for filter

### ISSUE THREAD

**Issue by SpirinEgor** [Voudy/Bestresto#2]
We need to implement checkboxes to filter encapsulated.

So, we have database, where we keep all types with sort parametr. When you want to open the filter, you get list of types in order by sort and add checkboxes in cycle.

It will be look like this:
`ArrayList<Type> checkboxes = getCheckboxes();`
`for (Types cur: checkboxes){`
   `addCheckbox(cur.name, cur.id):`
`}`

**Comment by SergeiGorbatiuk** [comment]
Dynamic setting implemented.
